### ISSUE TITLE
Replace console.logs with Winston loggers

### ISSUE THREAD

**Issue by RickyBaca28** [RickyBaca28/Fig-It#3]
# Description
Replace console.logs with Winston loggers

# Example of change in db.ts
## Before
``` Typescript
 console.log('Attempting to connect MongoDB!');
```

## After
``` Typescript
import Logger from './utils/logger;

const logger = logger.child({ label: 'fig-it:api:mongo' });
logger.info('Attempting to connect MongoDB!');
```

## Hint 
Check this out https://www.npmjs.com/package/winston
I expect a file called `logger.ts` in `backend/src/utils`

**Comment by mRenga** [comment]
hello world
